---
# For more information see base image README: https://hub.docker.com/r/unicon/shibboleth-idp/

version: "3"

services:
    shibboleth-idp-local:
        image: local/shibboleth-idp
        container_name: shibboleth-idp-local
        env_file: ./.env
        ports:
        - '443:4443'
        - '8443:8443'
        environment:
        - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=${JETTY_BROWSER_SSL_KEYSTORE_PASSWORD}
        - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=${JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD}
        - JETTY_MAX_HEAP=${JETTY_MAX_HEAP}
        volumes:
        - ./logs:/opt/shibboleth-idp/logs
        #- ./credentials:/opt/shibboleth-idp/credentials

